### PR TITLE
Must focus on interactive container

### LINKED ISSUE #125: Not focusing on non-clickable container
## Describe the bug:

Testing on [Accrescent](https://github.com/accrescent/accrescent), I noticed that the app is not focusing on the container of the selected option in the bottom bar, only on its internal text, unlike Talkback. This must be happening because the container has become non-clickable, and the logic to focus on the container evaluates only if is clickable.

## To Reproduce:

Test the bottom bar of Accrencent carefully, although the announced text is the same, you will notice that it is much more difficult to focus on the selected option. This happens because you can only focus on a tiny text of it.

## Expected behavior

It should focus when there is interaction, just like elements with intrinsic content (text, contentDescription etc).

## Screenshots:

Talkback

https://github.com/NeoA11y/SpeakTouch/assets/45833588/4cb2af12-a5bc-4737-af6d-f25436898a34

Speak Touch 

https://github.com/NeoA11y/SpeakTouch/assets/45833588/fce196eb-c068-4fe1-825c-240d959a4077

## More infos:
App version: 1.0.0-DEV
Android version: Irrelevant
Device: Irrelevant

### PR DESCRIPTION
**Pull request by Irineu333**
### Description

Read the issue  #125

### Improvements
- Focus on interactive container 

### Fixed issues
- Not focusing on non-clickable container

### CODE REVIEW

File: app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt [hunk 1]
```diff
@@ -97,7 +97,7 @@ object NodeValidator {
 
         if (mustReadContent(node)) return false
 
-        return isClickable(node) && hasReadableChild(node)
+        return hasInteraction(node) && hasReadableChild(node)
```
Comment (Irineu333) [inline app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt:100]: This fixes the bug but causes another one. It is focusing on the RecyclerView of the 'history' section of the Kotatsu app, a behavior that diverges from Talkback. I will do some tests to determine if the validation is wrong or if lists are an exception

Comment (Irineu333) [inline app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt]: This fixes the bug but causes another one. It is focusing on the `RecyclerView` of the 'history' section of the [Kotatsu](https://github.com/KotatsuApp/Kotatsu) app, a behavior that diverges from **Talkback**. I will do some tests to determine if the validation is wrong or if lists are an exception

**Review by PatrykMis — APPROVED** [review]
For non-Compose apps, it doesn't make difference as containers are properly focusing.

For Compose apps like Accrescent, it makes difference because: 
a) it focus all container, not just text; 
b) for bottom sheet tabs it announces now which one is chosen.

File: app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt (hunk 1 above)
Comment (Irineu333) [reply app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt]: Fixed in the commit [61a21aa9](https://github.com/NeoA11y/SpeakTouch/pull/126/commits/61a21aa932bd15016959c66f383aa0fd9b4aa375), I added a test case in the test module.

**Comment by Irineu333** [comment]
@coderabbitai review

File: buildSrc/settings.gradle.kts [hunk 2]
```diff
@@ -29,3 +29,7 @@ dependencyResolutionManagement {
         }
     }
 }
+
+plugins {
+    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
+}
```
Comment (Irineu333) [inline buildSrc/settings.gradle.kts:35]: Unable to download the specified JDK.

```
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@3ccc7b25 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':buildSrc'.
      > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
         > No matching toolchains found for requested specification: {languageVersion=17, vendor=ADOPTIUM, implementation=vendor-specific} for LINUX on x86_64.
            > No locally installed toolchains match and toolchain download repositories have not been configured.
```

Comment (PatrykMis) [reply buildSrc/settings.gradle.kts:35]: Have you managed to solve it already?

Comment (Irineu333) [reply buildSrc/settings.gradle.kts:35]: Yes, this change solves it.

Comment (PatrykMis) [reply buildSrc/settings.gradle.kts:35]: It's really interesting as I didn't have that error even without this change. I took another approach in https://github.com/NeoA11y/SpeakTouch/pull/131/commits/6257e6cdb2196447ee81b0bc1d4daef0bf4d4c69

Comment (PatrykMis) [reply buildSrc/settings.gradle.kts:35]: Ah, probably I understand now. You would like correct JDK to be downloaded while trying to build on another machine with e.g. JDK 21 installed.

Comment (Irineu333) [reply buildSrc/settings.gradle.kts:35]: Yes, I realized it wasn't working properly because I took advantage of the recess to change my development setup. I installed open jdk and not temurin specifically, and then it threw an error during the build. As we specified the adoptium distro in the toolchain, even though the version was correct, since the distro was wrong, it wouldn't allow the build. But thanks to [Foojay Toolchains](https://github.com/gradle/foojay-toolchains), it should have been able to download and configure the correct distro on its own, which didn't happen.

From what I understand, since the toolchain was configured in buildSrc, Foojay Toolchains should have been too, which is why it didn't work.
